### ISSUE TITLE
Discrepancy in fire names in xBD dataset?

### ISSUE THREAD

**Issue by kkraoj** [DIUx-xView/xView2_baseline#13]
Firstly, a BIG thanks for providing this dataset for research. 

I have a question: Where exactly is "Socal fire" data from? In Table 1 of your [manuscript ](https://arxiv.org/pdf/1911.09296.pdf), I don't see any fire labeled as "Socal fire", but in the [xview2 dataset](https://xview2.org/dataset), there are many images with names starting with "socal-fire". 

Additionally, Table 1 of the manuscript has a row for "Carr fire", but I did not find any images with names containing "Carr". Can you please help me figure out-
1. Which geographic location or which fire is "Socal fire" data from?
2. Is Carr fire data indeed missing (since no files contain the word "Carr" in `train`, `tier3`, or `test` folders)? 

Thanks again for all your efforts. I really appreciate it.

**Comment by yangsiyu007** [comment]
I have the same question! Which data files correspond to Carr Wildfire 2018 referenced in the manuscript? I think Carr Wildfire was in northern California, so it doesn't seem to correspond to the "socal fire" images...

**Comment by RitwikGupta** [comment]
Sorry for getting to this so late. @kkraoj @yangsiyu007 You're right, I have no idea where Carr went. I'm looking into it now. W.r.t. Socal fires, they correspond to the fires in Ventura County in 2017.

**Comment by RitwikGupta** [comment]
Just as an update, something's up with Carr. It was never released on our public website for some reason. We're still digging into why that happened and how to release it going forward. Give us a few weeks since it's break and there are some other things going on as well!

**Comment by RitwikGupta** [comment]
@kkraoj @yangsiyu007 Here's the much awaited conclusion on Carr: due to a breakdown in our dataset tracking, the Carr dataset was never labeled. What does this mean for xBD? Nothing much. All statistics that are shown in the paper are computed from the imagery that is actually present. As of now, we do not have funding to get the Carr dataset labeled.

So sorry about this. It was disappointing to dig into it and discover this as well. Luckily, fires are well-represented in xBD, so I hope this is not a hurdle to your research.

**Comment by RitwikGupta** [comment]
I should add, we'll correct the manuscript to address this discrepancy.
